### ISSUE TITLE
Make app looks good on mobile

### ISSUE THREAD

**Issue by ydcjeff** [pytorch-ignite/code-generator#104]
### Clear and concise description of the problem

We are currently able to visit the site even on mobile, but it doesn't look good.

### Suggested solution

Make app looks good with left sidebar and generated code in the middle.

### Alternative

N/A

**Comment by ydcjeff** [comment]
Is this GitHub bug? Not closing automatically?

**Comment by trsvchn** [comment]
Interesting...
but on the right we see:
> Successfully merging a pull request may close this issue.
MAY close... :)) so
it's might be a bug)
