### ISSUE TITLE
UI and templates improvements v0.2.0

### ISSUE THREAD

**Issue by vfdev-5** [pytorch-ignite/code-generator#136]
## Vision template

- [x] Configurable parts are not inplace and can lead to bad rendering: 

<img width="663" alt="Screen Shot 2021-05-25 at 21 50 38" src="https://user-images.githubusercontent.com/2459423/119559662-4501d900-bda3-11eb-885c-9c039fb5f338.png">

<img width="329" alt="Screen Shot 2021-05-25 at 21 51 50" src="https://user-images.githubusercontent.com/2459423/119559819-74b0e100-bda3-11eb-9667-07cbe165d0d8.png">
<img width="547" alt="Screen Shot 2021-05-25 at 21 51 58" src="https://user-images.githubusercontent.com/2459423/119559825-75e20e00-bda3-11eb-96df-48ab875befbf.png">

- [x] Unclear configuration name "every save_every_iters" and no related widget :

<img width="693" alt="Screen Shot 2021-05-25 at 21 52 29" src="https://user-images.githubusercontent.com/2459423/119559900-8c886500-bda3-11eb-94bb-f34895a3789a.png">

- [x] Put `dataloader_train.sampler.set_epoch(trainer.state.epoch - 1)` into `trainer = setup_trainer(config, model, optimizer, loss_fn, device, dataloader_train)`

## DCGAN template

~- [ ] We can remove `Net` model in `model.py`~

## Segmentation template

- [x] Put deeplabv3 model into model.py and remove Net and GANs models defs.
- [x] Unclear code
```python
    # run evaluation at every training epoch end
    # with shortcut `on` decorator API and
    # print metrics to the stderr
    # again with `add_event_handler` API
    # for evaluation stats
    @trainer.on(Events.EPOCH_COMPLETED(every=1))
    def _():
        # show timer
        
        if timer is not None:
            logger.info("Time per batch: %.4f seconds", timer.value())
            timer.reset()
```
What is the purpose of the timers and the reset here ?

**Comment by ydcjeff** [comment]
We have many if else in ejs and when rendered ejs didn't trim whitespaces.

**Comment by ydcjeff** [comment]
>  We can remove Net model in model.py

So no weight init?

>  Put deeplabv3 model into model.py and remove Net and GANs models defs.

There is no gan model def in segmentation

**Comment by ydcjeff** [comment]
Again GitHub didn't close it.
