### ISSUE TITLE
Show `txt` for requirements.txt in `CodeBlock`

### ISSUE THREAD

**Issue by ydcjeff** [pytorch-ignite/code-generator#164]
### Describe the bug

Currently, there is no file extension beside `Copy` button for `requirements.txt`.

![Screen Shot 2021-07-09 at 13 04 43](https://user-images.githubusercontent.com/32727188/125042203-964df980-e0bf-11eb-9a61-70c03d02d9bc.png)

### Expected result

Show `txt` beside `Copy` button.

### Steps to reproduce

1. Go to https://code-generator.netlify.app/create
2. Choose a template
3. See the `requirements.txt` in the right pane

### Solution

Currently, we are using [`markup`](https://github.com/pytorch-ignite/code-generator/blob/66b67cdb189a358377ee7dc98c15d1dc9a91cdad/src/components/CodeBlock.vue#L46) language from [Prismjs](https://prismjs.com/#supported-languages) for `txt` file which is not correct.

So change the `language-markup` to `language-txt` or `language-text` which don't exist in Prismjs languages. But this could allow us to add the file extension like [here](https://github.com/pytorch-ignite/code-generator/blob/66b67cdb189a358377ee7dc98c15d1dc9a91cdad/src/components/CodeBlock.vue#L152-L153).

Another part is we are highlighting [`txt` with `markup`](https://github.com/pytorch-ignite/code-generator/blob/66b67cdb189a358377ee7dc98c15d1dc9a91cdad/src/components/CodeBlock.vue#L52). Since text files normally don't need syntax highlighting, we could just pass language grammar as empty object (i.e. `languages['markup']` -> `{}`).

---

_If you like to tackle this issue, please comment that you want to work on and see the [contributing guide](https://github.com/pytorch-ignite/code-generator/blob/main/CONTRIBUTING.md)_.

**Comment by afzal442** [comment]
hi there, I would like to look into this.

/assign

**Comment by trsvchn** [comment]
@afzal442 Sure! Go for it!
