### ISSUE TITLE
Add 404 page

### ISSUE THREAD

**Issue by vfdev-5** [pytorch-ignite/code-generator#170]
### Clear and concise description of the problem

If going to any unexpected url e.g. `https://code-generator.pytorch-ignite.ai/test`, we see a blank page. 
Let's show a 404 page ?

**Comment by afzal442** [comment]
Giving it a shot as well!

**Comment by trsvchn** [comment]
@afzal442 Thank you for your interest in PyTorch-Ignite's CodeGenerator!
Feel free to ask if any help is needed!
