### ISSUE TITLE
fix nav bar in 404 page

### ISSUE THREAD

**Issue by ydcjeff** [pytorch-ignite/code-generator#180]
### Describe the bug

Nav bar became too large in 404 page and covered the h1 title.

![Screen Shot 2021-10-05 at 10 45 05](https://user-images.githubusercontent.com/32727188/135959131-b9e44f16-e9e0-44a8-bf27-487344d449b1.png)

### Expected result

NavBar not covered the h1 title.

### Reproduction

https://code-generator.pytorch-ignite.ai/foobar

### Steps to reproduce

View the reproduction link on mobile

**Comment by B1TSH3LL** [comment]
I Can Work On This Issue Please Assign It To Me :)

**Comment by rwiteshbera** [comment]
I can work on this issue, can you please assign me this issue? @ydcjeff
