### ISSUE TITLE
Update torch.distributed.launch to torchrun

### ISSUE THREAD

**Issue by vfdev-5** [pytorch-ignite/code-generator#199]
`torch.distributed.launch` is be deprecated, let's use recommended launcher. Related ignite issue: https://github.com/pytorch/ignite/issues/2415

**Comment by vfdev-5** [comment]
@sayantan1410 would you like to tackle this one ?

**Comment by sayantan1410** [comment]
@vfdev-5 yeah, sure I would love to tackle this ?
