### ISSUE TITLE
Boolean config item always give 'False' value.

### ISSUE THREAD

**Issue by idkwid2022** [pytorch-ignite/code-generator#216]
### Describe the bug

Boolean config items always give 'False' value even when set 'True' or 'true' in config.yaml.

Please see function setup_parser() on utils.py, on line 29. I think it's missing default value, like on line 31, or may be just skip checking the boolean type, and treat it like another?

https://github.com/pytorch-ignite/code-generator/blob/f1372194000fb461c9e3eb7f4f85f43ad8f61a6c/src/templates/template-vision-segmentation/utils.py#L21-L33

### Expected result

Boolean config items give value as set.

### Steps to reproduce

Set any boolean config item in config.yaml to 'true'.

**Comment by vfdev-5** [comment]
Thanks for reporting @idkwid2022 !
I have to check details. As far as I know for arg parser to pass boolean flag is done with "store_true" action as it should not work correctly if we're using type and default args as for other types. Maybe the issue is elsewhere...

**Comment by idkwid2022** [comment]
I think it's because how it's used in this project.

My understanding is function `setup_parser` is correct as is, if it's intended only to setup the parser, but because on main.py you did not pass any value at all:

https://github.com/pytorch-ignite/code-generator/blob/f1372194000fb461c9e3eb7f4f85f43ad8f61a6c/src/templates/template-vision-segmentation/main.py#L197-L220

When we run `python main.py`, the parser will not have any argument value at all, and `action="store_true"` will give `False` as default value. 

But if the intended purpose was to just use `config.yaml`, it's incorrect. 

I modify mine to skip the type checking:
~~~
def setup_parser():
    with open("config.yaml", "r") as f:
        config = yaml.safe_load(f.read())

    parser = ArgumentParser()
    parser.add_argument("--backend", default=None, type=str)
    for k, v in config.items():
        parser.add_argument(f"--{k}", default=v, type=type(v))

    return parser
~~~

**Comment by vfdev-5** [comment]
I see your point. I tried your solution and default one. Actually, the point is the following:
Currently, `config.yaml` defines config variables and their default values and for boolean as you stated no matter the value is in `config.yaml`, config object will have `False`. To make it as True on execution we need to call:
```bash
python main.py --debug --use_amp
```
so, that config object will have `config.debug == True` and `config.use_amp == True`.
If we take the change you proposed in your comment, then `python main.py --debug` wont work anymore. And further more it lead to the following issue: `python main.py --debug=False` -> `config.debug == True`
On the other hand I agree with you that we should be able to override `config.yaml` boolean vars and set default value as True.

@ydcjeff can you suggest what we should do here ?

**Comment by vfdev-5** [comment]
Maybe, we can update `setup_parser()` as following:
```python
def setup_parser():
    with open("config.yaml", "r") as f:
        config = yaml.safe_load(f.read())

    parser = ArgumentParser()
    parser.add_argument("--backend", default=None, type=str)
    for k, v in config.items():
        if isinstance(v, bool):
            prefix = "" if not v else "no_"
            parser.add_argument(
                f"--{prefix}{k}", dest=f"{k}", action=f"store_{str(not v).lower()}"
            )
        else:
            parser.add_argument(f"--{k}", default=v, type=type(v))

    return parser
```

So, it will behave as following with config.yaml:
```
debug: false
use_amp: true
```

1) Default values:
```
python main.py
> config.debug==False, config.use_amp==True
```

2) Override `debug` to True
```
python main.py --debug
> config.debug==True, config.use_amp==True
```

3) Override `use_amp` to False
```
python main.py --no_use_amp
> config.debug==False, config.use_amp==False
```

@idkwid2022 what do you think ?

**Comment by idkwid2022** [comment]
I think it's good, but if for ignorance guy like me, I think it should be mentioned in the README.md.

I got this problem because I read 

https://github.com/pytorch-ignite/code-generator/blob/f1372194000fb461c9e3eb7f4f85f43ad8f61a6c/src/templates/template-vision-segmentation/README.md?plain=1#L114

and immediately assumed everything will be set with `config.yaml`, the other lines (`backend`, `nproc_per_node`, etc.) didn't show because I didn't use distributed training. And I was ignorance enough to not think about setting arguments with command line. And it worked with other items like `train_batch_size`, `data-path`, etc.

**Comment by vfdev-5** [comment]
Yes, you are right, we should have mentioned that in Readme !

Would you like to send a PR with the fixes:
1) for setup_parser and 2) for Readme ?

**Comment by idkwid2022** [comment]
I'm gonna have to leave it here for now. I'm already overwhelmed with so much things in image segmentation topic. I think it's good enough for now that the issue is raised and we already have your solution here. 

So, I think this can be closed.

**Comment by theory-in-progress** [comment]
With the new config system in the PR #243 https://github.com/pytorch-ignite/code-generator/blob/9393a0458954bdd4fb0d3caf68312b710b4ea0a9/src/templates/template-common/utils.py#L44-L74 The  attributes are set accordingly. I don't think the problem exists now.
