### ISSUE TITLE
Let's make `train_epoch_length` and `eval_epoch_length` optional

### ISSUE THREAD

**Issue by vfdev-5** [pytorch-ignite/code-generator#233]
Config `config.yaml` files require two params: `train_epoch_length` and `eval_epoch_length`
Let's make them optional.

https://github.com/pytorch-ignite/code-generator/blob/a2bee40570c65048b8a803e0a016adde2fe41ddc/src/templates/template-vision-segmentation/config.yaml#L7-L8

Such that epoch length is defined by the input dataloaders.

**Comment by DeepC004** [comment]
I can take up the issue

**Comment by DeepC004** [comment]
@vfdev-5 I have a doubt regarding the optional values. Aren't the values specified for `train_length_epoch` and `eval_length_epoch` already the default ones? Incase the user does not input a custom value for a parameter then default ones will be used as defined by the code.
