### ISSUE TITLE
add resume options to resume training properly

### ISSUE THREAD

**Issue by jeffydc** [pytorch-ignite/code-generator#31]
Add a `resume_from` option to load a checkpoint (https://, str, Path) using
- [Checkpoint.load_objects](https://pytorch.org/ignite/master/generated/ignite.handlers.checkpoint.Checkpoint.html#ignite.handlers.checkpoint.Checkpoint.load_objects)

Ref : [deit](https://github.com/facebookresearch/deit/blob/ab5715372db8c6cad5740714b2216d55aeae052e/main.py#L348), [ignite cifar10](https://github.com/pytorch/ignite/blob/711a9911cd57fd619090247dc5a1d9c3215cfd05/examples/contrib/cifar10/main.py#L345)

**Comment by jo7ueb** [comment]
I'm looking current code.
`resume_from()` exists in `utils.py` but nobody is calling it.
