### ISSUE TITLE
Dark Mode for the Code Generator App

### ISSUE THREAD

**Issue by guptaaryan16** [pytorch-ignite/code-generator#336]
### Clear and concise description of the problem

We can add a dark mode for the Code Generator app that is similar to the `PyTorch Ignite` docs and that would be helpful for the users as well.

### Suggested solution
You can look at https://pytorch-ignite.ai for more information about the Dark mode for the website and the colour scheme that can be used.

**Comment by ShatilKhan** [comment]
Hi 
I'm new to the community
I'd love to take on this issue

**Comment by avinashsharma080** [comment]
Hi, I would like to help with this issue
Just to be clear where are we planning to put button on code generator webpage?

**Comment by vfdev-5** [comment]
> Hi, I would like to help with this issue Just to be clear where are we planning to put button on code generator webpage?

Yes, same as on pytorch-ignite.ai site:
<img width="277" alt="image" src="https://github.com/pytorch-ignite/code-generator/assets/2459423/8d6b7f33-3789-4191-a808-94b1726afde3">
