### ISSUE TITLE
Use wget with download link

### ISSUE THREAD

**Issue by vfdev-5** [pytorch-ignite/code-generator#95]
It would be nice to be able to download the link using wget-like tools and not only the browser.

cc @trsvchn

**Comment by afzal442** [comment]
Giving it a go!

/assign

**Comment by afzal442** [comment]
hi there,
could you be a little more explicit here like how do you want this to be enabled? I think we can allow the user to download the link for `wget` command. e.g. !wget `https://raw.githubusercontent.com/trsvchn-lab/nbs/main/nbs/02622a4b-a6f6-4a78-9030-a11eba638092/ignite-template-vision-classification.zip`
Is there a kind of feat that exist somewhere else? let me know if any, thanks.

**Comment by trsvchn** [comment]
Hi @afzal442 !
I see it in this way. Code Generator renders python files and generates archive on client side, so there is no static links for wget to work with. Currently we have 2 options:
- "Download"        <-- archive is generated in a browser, and downloaded via browser
- "Open in Colab" <-- archive is generated in a browser, but then pushed to GH

So my idea is to add third option "Download with wget" that reuses "Open in Colab" functionality, thus no spam requests to GH.

@vfdev-5 @ydcjeff what do you think?

**Comment by ydcjeff** [comment]
Yes, we can reuse the function from "Open in Colab" for downloading with wget.
